# Generated by Django 5.2.17 on 2026-08-12 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='bale_pay', max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'شروع\u200cشده'), ('success', 'موفق'), ('failed', 'ناموفق')], default='initiated', max_length=15)),
                ('gateway_token', models.CharField(blank=True, db_index=True, help_text='توکن/شناسه ایجاد تراکنش از درگاه', max_length=100)),
                ('gateway_ref_id', models.CharField(blank=True, help_text='کد پیگیری نهایی بعد از تایید پرداخت', max_length=100)),
                ('raw_response', models.JSONField(blank=True, help_text='پاسخ خام درگاه، برای دیباگ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
