# Generated by Django 5.2.17 on 2026-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='آتلار', max_length=80)),
                ('tagline', models.CharField(blank=True, default='پارچه مبلی، مستقیم از تولید تا خانه شما', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('phone_display', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس نمایشی')),
                ('instagram_username', models.CharField(blank=True, max_length=60)),
                ('telegram_username', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('default_fabric_width_cm', models.PositiveSmallIntegerField(default=140, help_text='عرض طاقه برای همه\u200cی پارچه\u200cهای فروشگاه ثابته — فقط همین یک\u200cجا تنظیمش کن.', verbose_name='عرض رول پارچه (سانتی\u200cمتر)')),
                ('default_shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال (تومان)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=0, help_text='خالی بگذار اگر ارسال رایگان نداری.', max_digits=10, null=True, verbose_name='حداقل خرید برای ارسال رایگان (تومان)')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
