# Generated by Django 5.2.17 on 2026-08-16 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='آدرس اصلی', max_length=80, verbose_name='عنوان آدرس')),
                ('address_line', models.CharField(max_length=300, verbose_name='آدرس')),
                ('city', models.CharField(max_length=80, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید به فرم ۰۹xxxxxxxxx وارد شود.', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
