# Generated by Django 5.2.17 on 2026-09-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_security'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['session_key'], name='accounts_ot_session_44a43b_idx'),
        ),
    ]
