# Generated by Django 5.2.17 on 2026-09-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_session_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='توضیحات اضافی'),
        ),
        migrations.AddField(
            model_name='address',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='پلاک'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=300, verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
    ]
