# Generated by Django 5.2.17 on 2026-08-12 19:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال\u200cشده'), ('delivered', 'تحویل داده\u200cشده'), ('cancelled', 'لغوشده')], default='pending_payment', max_length=20)),
                ('full_name', models.CharField(max_length=120, verbose_name='نام گیرنده')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید به فرم ۰۹xxxxxxxxx وارد شود.', regex='^09\\d{9}$')])),
                ('address_line', models.CharField(max_length=300, verbose_name='آدرس')),
                ('city', models.CharField(max_length=80, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=150)),
                ('color_name', models.CharField(blank=True, max_length=60)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity_meters', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.fabriccolorvariant')),
            ],
            options={
                'verbose_name': 'ردیف سفارش',
                'verbose_name_plural': 'ردیف\u200cهای سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
    ]
