# Generated by Django 5.2.17 on 2026-08-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('orders', '0002_order_email_alter_order_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد تخفیف')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'ثابت')], default='percent', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مقدار تخفیف')),
                ('min_order_total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداقل مبلغ سفارش')),
                ('max_discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حداکثر تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('usage_limit', models.PositiveIntegerField(default=0, verbose_name='محدودیت استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address', verbose_name='آدرس ثبت\u200cشده'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discount', verbose_name='تخفیف اعمال\u200cشده'),
        ),
    ]
