# Generated by Django 5.2.17 on 2026-08-12 19:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام کالیته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True)),
                ('sku', models.CharField(blank=True, max_length=40, unique=True, verbose_name='کد کالا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pattern', models.CharField(blank=True, help_text='مثلاً: ساده، طرح\u200cدار، گلدار، هندسی', max_length=60, verbose_name='طرح')),
                ('material', models.CharField(blank=True, help_text='مثلاً: ۱۰۰٪ پلی\u200cاستر', max_length=120, verbose_name='جنس')),
                ('abrasion_rating', models.PositiveIntegerField(blank=True, help_text='تعداد چرخه تست مارتیندل — هرچه بیشتر، بادوام\u200cتر.', null=True, verbose_name='مقاومت سایش (مارتیندل)')),
                ('is_fire_retardant', models.BooleanField(default=False, verbose_name='ضد حریق')),
                ('is_washable', models.BooleanField(default=False, verbose_name='قابل شست\u200cوشو')),
                ('price_per_meter', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت هر متر (تومان)')),
                ('min_order_meters', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=4, verbose_name='حداقل سفارش (متر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / نمایش در سایت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabrics', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کالیته پارچه',
                'verbose_name_plural': 'کالیته\u200cهای پارچه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FabricColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=60, verbose_name='نام رنگ')),
                ('color_hex', models.CharField(blank=True, help_text='برای نمایش دایره\u200cی رنگ، مثلاً #7a1f2b — خالی بگذار اگر نمی\u200cدونی.', max_length=7, verbose_name='کد رنگ (اختیاری)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabrics/variants/', verbose_name='تصویر این رنگ')),
                ('stock_meters', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=8, verbose_name='موجودی (متر)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.fabric', verbose_name='کالیته')),
            ],
            options={
                'verbose_name': 'رنگ\u200cبندی',
                'verbose_name_plural': 'رنگ\u200cبندی\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fabrics/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.fabriccolorvariant', verbose_name='رنگ\u200cبندی')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['is_active', 'category'], name='products_fa_is_acti_70c738_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_fa_is_acti_b84c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='fabric',
            index=models.Index(fields=['slug'], name='products_fa_slug_a807c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fabriccolorvariant',
            unique_together={('fabric', 'color_name')},
        ),
    ]
