# Generated by Django 5.2.17 on 2026-08-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='is_fire_retardant',
        ),
    ]
